// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  --hdl verilog --gen-hdl ../src/multiflex_regs.v --input multiflex_regs.yaml
// Generated on Wed Apr 08 19:34:18 2026 by akiel



module multiflex_regs
  (
    input   wire pclk,
    input   wire presetn,
    input   wire [14:2] paddr,
    input   wire psel,
    input   wire pwrite,
    input   wire penable,
    output  wire pready,
    input   wire [31:0] pwdata,
    input   wire [3:0] pstrb,
    output  wire [31:0] prdata,
    output  wire pslverr,

    // REG ctrl
    output  wire ctrl_enable_o,
    output  wire [4:0] ctrl_lanes_tx_o,
    output  wire [4:0] ctrl_lanes_rx_o,
    output  wire [7:0] ctrl_clk_div_o,
    output  wire ctrl_loopback_o,

    // REG status
    input   wire status_tx_busy_i,
    input   wire status_tx_full_i,
    input   wire status_tx_empty_i,
    input   wire status_tx_overflow_i,
    input   wire status_rx_locked_i,
    input   wire status_rx_clk_timeout_i,
    input   wire status_rx_sync_lost_i,
    input   wire status_rx_framing_err_i,

    // REG tx_data
    output  wire [7:0] tx_data_data_o,

    // REG rx_data
    input   wire [7:0] rx_data_data_i,
    input   wire rx_data_valid_i,

    // REG error_cnt
    input   wire [7:0] error_cnt_tx_drop_count_i,
    input   wire [7:0] error_cnt_rx_error_count_i,

    // REG error_clr
    output  wire error_clr_clr_tx_o,
    output  wire error_clr_clr_rx_o,

    // REG tx_len
    output  wire [10:0] tx_len_len_o,

    // REG rx_count
    input   wire [10:0] rx_count_count_i,

    // RAM port for tx_buf
    input   wire [10:0] tx_buf_adr_i,
    input   wire tx_buf_data_rd_i,
    output  wire [7:0] tx_buf_data_dat_o,

    // RAM port for rx_buf
    input   wire [10:0] rx_buf_adr_i,
    input   wire rx_buf_data_we_i,
    input   wire [7:0] rx_buf_data_dat_i
  );
  wire wr_req;
  wire [14:2] wr_addr;
  wire [31:0] wr_data;
  reg [31:0] wr_sel;
  wire rd_req;
  wire [14:2] rd_addr;
  reg [31:0] rd_data;
  reg wr_ack;
  reg rd_ack;
  reg ctrl_enable_reg;
  reg [4:0] ctrl_lanes_tx_reg;
  reg [4:0] ctrl_lanes_rx_reg;
  reg [7:0] ctrl_clk_div_reg;
  reg ctrl_loopback_reg;
  reg ctrl_wreq;
  wire ctrl_wack;
  reg [7:0] tx_data_data_reg;
  reg tx_data_wreq;
  wire tx_data_wack;
  reg error_clr_clr_tx_reg;
  reg error_clr_clr_rx_reg;
  reg error_clr_wreq;
  wire error_clr_wack;
  reg [10:0] tx_len_len_reg;
  reg tx_len_wreq;
  wire tx_len_wack;
  wire [7:0] tx_buf_data_int_dato;
  wire [7:0] tx_buf_data_ext_dat;
  reg tx_buf_data_rreq;
  reg tx_buf_data_rack;
  reg tx_buf_data_int_wr;
  wire [7:0] rx_buf_data_int_dato;
  wire [7:0] rx_buf_data_ext_dat;
  reg rx_buf_data_rreq;
  reg rx_buf_data_rack;
  reg rd_ack_d0;
  reg [31:0] rd_dat_d0;
  reg wr_req_d0;
  reg [14:2] wr_adr_d0;
  reg [31:0] wr_dat_d0;
  reg [31:0] wr_sel_d0;
  wire tx_buf_wr;
  wire tx_buf_wreq;
  reg [10:0] tx_buf_adr_int;
  reg [3:0] tx_buf_sel_int;
  reg [3:0] rx_buf_sel_int;

  // Write Channel
  assign wr_req = (psel & pwrite) & ~penable;
  assign wr_addr = paddr;
  assign wr_data = pwdata;
  always @(pstrb)
  begin
    wr_sel[7:0] = {8{pstrb[0]}};
    wr_sel[15:8] = {8{pstrb[1]}};
    wr_sel[23:16] = {8{pstrb[2]}};
    wr_sel[31:24] = {8{pstrb[3]}};
  end

  // Read Channel
  assign rd_req = (psel & ~pwrite) & ~penable;
  assign rd_addr = paddr;
  assign prdata = rd_data;
  assign pready = wr_ack | rd_ack;
  assign pslverr = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        rd_ack <= 1'b0;
        rd_data <= 32'b00000000000000000000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 13'b0000000000000;
        wr_dat_d0 <= 32'b00000000000000000000000000000000;
        wr_sel_d0 <= 32'b00000000000000000000000000000000;
      end
    else
      begin
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
        wr_sel_d0 <= wr_sel;
      end
  end

  // Register ctrl
  assign ctrl_enable_o = ctrl_enable_reg;
  assign ctrl_lanes_tx_o = ctrl_lanes_tx_reg;
  assign ctrl_lanes_rx_o = ctrl_lanes_rx_reg;
  assign ctrl_clk_div_o = ctrl_clk_div_reg;
  assign ctrl_loopback_o = ctrl_loopback_reg;
  assign ctrl_wack = ctrl_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        ctrl_enable_reg <= 1'b0;
        ctrl_lanes_tx_reg <= 5'b00000;
        ctrl_lanes_rx_reg <= 5'b00000;
        ctrl_clk_div_reg <= 8'b00000000;
        ctrl_loopback_reg <= 1'b0;
      end
    else
      if (ctrl_wreq == 1'b1)
        begin
          ctrl_enable_reg <= wr_dat_d0[0];
          ctrl_lanes_tx_reg <= wr_dat_d0[5:1];
          ctrl_lanes_rx_reg <= wr_dat_d0[10:6];
          ctrl_clk_div_reg <= wr_dat_d0[18:11];
          ctrl_loopback_reg <= wr_dat_d0[19];
        end
  end

  // Register status

  // Register tx_data
  assign tx_data_data_o = tx_data_data_reg;
  assign tx_data_wack = tx_data_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      tx_data_data_reg <= 8'b00000000;
    else
      if (tx_data_wreq == 1'b1)
        tx_data_data_reg <= wr_dat_d0[7:0];
  end

  // Register rx_data

  // Register error_cnt

  // Register error_clr
  assign error_clr_clr_tx_o = error_clr_clr_tx_reg;
  assign error_clr_clr_rx_o = error_clr_clr_rx_reg;
  assign error_clr_wack = error_clr_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        error_clr_clr_tx_reg <= 1'b0;
        error_clr_clr_rx_reg <= 1'b0;
      end
    else
      if (error_clr_wreq == 1'b1)
        begin
          error_clr_clr_tx_reg <= wr_dat_d0[0];
          error_clr_clr_rx_reg <= wr_dat_d0[1];
        end
  end

  // Register tx_len
  assign tx_len_len_o = tx_len_len_reg;
  assign tx_len_wack = tx_len_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      tx_len_len_reg <= 11'b00000000000;
    else
      if (tx_len_wreq == 1'b1)
        tx_len_len_reg <= wr_dat_d0[10:0];
  end

  // Register rx_count

  // Memory tx_buf
  always @(rd_addr, wr_adr_d0, tx_buf_wr)
  if (tx_buf_wr == 1'b1)
    tx_buf_adr_int = wr_adr_d0[12:2];
  else
    tx_buf_adr_int = rd_addr[12:2];
  assign tx_buf_wreq = tx_buf_data_int_wr;
  assign tx_buf_wr = tx_buf_wreq;
  cheby_dpssram #(
      .g_data_width(8),
      .g_size(2048),
      .g_addr_width(11),
      .g_dual_clock(1'b0),
      .g_use_bwsel(1'b1)
    )
  tx_buf_data_raminst (
      .clk_a_i(pclk),
      .clk_b_i(pclk),
      .addr_a_i(tx_buf_adr_int),
      .bwsel_a_i(tx_buf_sel_int[0:0]),
      .data_a_i(wr_dat_d0[7:0]),
      .data_a_o(tx_buf_data_int_dato),
      .rd_a_i(tx_buf_data_rreq),
      .wr_a_i(tx_buf_data_int_wr),
      .addr_b_i(tx_buf_adr_i),
      .bwsel_b_i({1{1'b1}}),
      .data_b_i(tx_buf_data_ext_dat),
      .data_b_o(tx_buf_data_dat_o),
      .rd_b_i(tx_buf_data_rd_i),
      .wr_b_i(1'b0)
    );
  
  always @(wr_sel_d0)
  begin
    tx_buf_sel_int = 4'b0;
    if (~(wr_sel_d0[7:0] == 8'b0))
      tx_buf_sel_int[0] = 1'b1;
    if (~(wr_sel_d0[15:8] == 8'b0))
      tx_buf_sel_int[1] = 1'b1;
    if (~(wr_sel_d0[23:16] == 8'b0))
      tx_buf_sel_int[2] = 1'b1;
    if (~(wr_sel_d0[31:24] == 8'b0))
      tx_buf_sel_int[3] = 1'b1;
  end
  always @(posedge(pclk))
  begin
    if (!presetn)
      tx_buf_data_rack <= 1'b0;
    else
      tx_buf_data_rack <= (tx_buf_data_rreq & ~tx_buf_wreq) & ~tx_buf_data_rack;
  end

  // Memory rx_buf
  cheby_dpssram #(
      .g_data_width(8),
      .g_size(2048),
      .g_addr_width(11),
      .g_dual_clock(1'b0),
      .g_use_bwsel(1'b1)
    )
  rx_buf_data_raminst (
      .clk_a_i(pclk),
      .clk_b_i(pclk),
      .addr_a_i(rd_addr[12:2]),
      .bwsel_a_i(rx_buf_sel_int[0:0]),
      .data_a_i({8{1'bx}}),
      .data_a_o(rx_buf_data_int_dato),
      .rd_a_i(rx_buf_data_rreq),
      .wr_a_i(1'b0),
      .addr_b_i(rx_buf_adr_i),
      .bwsel_b_i({1{1'b1}}),
      .data_b_i(rx_buf_data_dat_i),
      .data_b_o(rx_buf_data_ext_dat),
      .rd_b_i(1'b0),
      .wr_b_i(rx_buf_data_we_i)
    );
  
  always @(wr_sel_d0)
  begin
    rx_buf_sel_int = 4'b0;
    if (~(wr_sel_d0[7:0] == 8'b0))
      rx_buf_sel_int[0] = 1'b1;
    if (~(wr_sel_d0[15:8] == 8'b0))
      rx_buf_sel_int[1] = 1'b1;
    if (~(wr_sel_d0[23:16] == 8'b0))
      rx_buf_sel_int[2] = 1'b1;
    if (~(wr_sel_d0[31:24] == 8'b0))
      rx_buf_sel_int[3] = 1'b1;
  end
  always @(posedge(pclk))
  begin
    if (!presetn)
      rx_buf_data_rack <= 1'b0;
    else
      rx_buf_data_rack <= rx_buf_data_rreq;
  end

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, ctrl_wack, tx_data_wack, error_clr_wack, tx_len_wack)
  begin
    ctrl_wreq = 1'b0;
    tx_data_wreq = 1'b0;
    error_clr_wreq = 1'b0;
    tx_len_wreq = 1'b0;
    tx_buf_data_int_wr = 1'b0;
    case (wr_adr_d0[14:13])
    2'b00:
      case (wr_adr_d0[12:2])
      11'b00000000000:
        begin
          // Reg ctrl
          ctrl_wreq = wr_req_d0;
          wr_ack = ctrl_wack;
        end
      11'b00000000001:
        // Reg status
        wr_ack = wr_req_d0;
      11'b00000000010:
        begin
          // Reg tx_data
          tx_data_wreq = wr_req_d0;
          wr_ack = tx_data_wack;
        end
      11'b00000000011:
        // Reg rx_data
        wr_ack = wr_req_d0;
      11'b00000000100:
        // Reg error_cnt
        wr_ack = wr_req_d0;
      11'b00000000101:
        begin
          // Reg error_clr
          error_clr_wreq = wr_req_d0;
          wr_ack = error_clr_wack;
        end
      11'b00000000110:
        begin
          // Reg tx_len
          tx_len_wreq = wr_req_d0;
          wr_ack = tx_len_wack;
        end
      11'b00000000111:
        // Reg rx_count
        wr_ack = wr_req_d0;
      default:
        wr_ack = wr_req_d0;
      endcase
    2'b01:
      begin
        // Memory tx_buf
        tx_buf_data_int_wr = wr_req_d0;
        wr_ack = wr_req_d0;
      end
    2'b10:
      // Memory rx_buf
      wr_ack = wr_req_d0;
    default:
      wr_ack = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(rd_addr, rd_req, ctrl_enable_reg, ctrl_lanes_tx_reg, ctrl_lanes_rx_reg, ctrl_clk_div_reg, ctrl_loopback_reg, status_tx_busy_i, status_tx_full_i, status_tx_empty_i, status_tx_overflow_i, status_rx_locked_i, status_rx_clk_timeout_i, status_rx_sync_lost_i, status_rx_framing_err_i, tx_data_data_reg, rx_data_data_i, rx_data_valid_i, error_cnt_tx_drop_count_i, error_cnt_rx_error_count_i, error_clr_clr_tx_reg, error_clr_clr_rx_reg, tx_len_len_reg, rx_count_count_i, tx_buf_data_int_dato, tx_buf_wreq, tx_buf_data_rack, rx_buf_data_int_dato, rx_buf_data_rack)
  begin
    // By default ack read requests
    rd_dat_d0 = {32{1'bx}};
    tx_buf_data_rreq = 1'b0;
    rx_buf_data_rreq = 1'b0;
    case (rd_addr[14:13])
    2'b00:
      case (rd_addr[12:2])
      11'b00000000000:
        begin
          // Reg ctrl
          rd_ack_d0 = rd_req;
          rd_dat_d0[0] = ctrl_enable_reg;
          rd_dat_d0[5:1] = ctrl_lanes_tx_reg;
          rd_dat_d0[10:6] = ctrl_lanes_rx_reg;
          rd_dat_d0[18:11] = ctrl_clk_div_reg;
          rd_dat_d0[19] = ctrl_loopback_reg;
          rd_dat_d0[31:20] = 12'b0;
        end
      11'b00000000001:
        begin
          // Reg status
          rd_ack_d0 = rd_req;
          rd_dat_d0[0] = status_tx_busy_i;
          rd_dat_d0[1] = status_tx_full_i;
          rd_dat_d0[2] = status_tx_empty_i;
          rd_dat_d0[3] = status_tx_overflow_i;
          rd_dat_d0[7:4] = 4'b0;
          rd_dat_d0[8] = status_rx_locked_i;
          rd_dat_d0[9] = status_rx_clk_timeout_i;
          rd_dat_d0[10] = status_rx_sync_lost_i;
          rd_dat_d0[11] = status_rx_framing_err_i;
          rd_dat_d0[31:12] = 20'b0;
        end
      11'b00000000010:
        begin
          // Reg tx_data
          rd_ack_d0 = rd_req;
          rd_dat_d0[7:0] = tx_data_data_reg;
          rd_dat_d0[31:8] = 24'b0;
        end
      11'b00000000011:
        begin
          // Reg rx_data
          rd_ack_d0 = rd_req;
          rd_dat_d0[7:0] = rx_data_data_i;
          rd_dat_d0[8] = rx_data_valid_i;
          rd_dat_d0[31:9] = 23'b0;
        end
      11'b00000000100:
        begin
          // Reg error_cnt
          rd_ack_d0 = rd_req;
          rd_dat_d0[7:0] = error_cnt_tx_drop_count_i;
          rd_dat_d0[15:8] = error_cnt_rx_error_count_i;
          rd_dat_d0[31:16] = 16'b0;
        end
      11'b00000000101:
        begin
          // Reg error_clr
          rd_ack_d0 = rd_req;
          rd_dat_d0[0] = error_clr_clr_tx_reg;
          rd_dat_d0[1] = error_clr_clr_rx_reg;
          rd_dat_d0[31:2] = 30'b0;
        end
      11'b00000000110:
        begin
          // Reg tx_len
          rd_ack_d0 = rd_req;
          rd_dat_d0[10:0] = tx_len_len_reg;
          rd_dat_d0[31:11] = 21'b0;
        end
      11'b00000000111:
        begin
          // Reg rx_count
          rd_ack_d0 = rd_req;
          rd_dat_d0[10:0] = rx_count_count_i;
          rd_dat_d0[31:11] = 21'b0;
        end
      default:
        rd_ack_d0 = rd_req;
      endcase
    2'b01:
      begin
        // Memory tx_buf
        rd_dat_d0 = {24'b000000000000000000000000, tx_buf_data_int_dato};
        tx_buf_data_rreq = rd_req & ~tx_buf_wreq;
        rd_ack_d0 = tx_buf_data_rack;
      end
    2'b10:
      begin
        // Memory rx_buf
        rd_dat_d0 = {24'b000000000000000000000000, rx_buf_data_int_dato};
        rx_buf_data_rreq = rd_req;
        rd_ack_d0 = rx_buf_data_rack;
      end
    default:
      rd_ack_d0 = rd_req;
    endcase
  end
endmodule
