// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  --hdl verilog --gen-hdl multiflex_regs.v --input multiflex_regs.yaml
// Generated on Sun Apr 05 13:09:43 2026 by akiel



module multiflex_regs
  (
    input   wire pclk,
    input   wire presetn,
    input   wire [4:2] paddr,
    input   wire psel,
    input   wire pwrite,
    input   wire penable,
    output  wire pready,
    input   wire [31:0] pwdata,
    input   wire [3:0] pstrb,
    output  wire [31:0] prdata,
    output  wire pslverr,

    // REG ctrl
    output  wire ctrl_enable_o,
    output  wire [4:0] ctrl_lanes_o,
    output  wire [7:0] ctrl_clk_div_o,
    output  wire ctrl_loopback_o,

    // REG status
    input   wire status_tx_busy_i,
    input   wire status_tx_full_i,
    input   wire status_tx_empty_i,
    input   wire status_tx_overflow_i,
    input   wire status_rx_locked_i,
    input   wire status_rx_clk_timeout_i,
    input   wire status_rx_sync_lost_i,
    input   wire status_rx_framing_err_i,
    input   wire status_rx_overflow_i,

    // REG tx_data
    output  wire [7:0] tx_data_data_o,

    // REG rx_data
    input   wire [7:0] rx_data_data_i,
    input   wire rx_data_valid_i,

    // REG error_cnt
    input   wire [7:0] error_cnt_tx_drop_count_i,
    input   wire [7:0] error_cnt_rx_error_count_i,

    // REG error_clr
    output  wire error_clr_clr_tx_o,
    output  wire error_clr_clr_rx_o
  );
  wire wr_req;
  wire [4:2] wr_addr;
  wire [31:0] wr_data;
  wire rd_req;
  wire [4:2] rd_addr;
  reg [31:0] rd_data;
  reg wr_ack;
  reg rd_ack;
  reg ctrl_enable_reg;
  reg [4:0] ctrl_lanes_reg;
  reg [7:0] ctrl_clk_div_reg;
  reg ctrl_loopback_reg;
  reg ctrl_wreq;
  wire ctrl_wack;
  reg [7:0] tx_data_data_reg;
  reg tx_data_wreq;
  wire tx_data_wack;
  reg error_clr_clr_tx_reg;
  reg error_clr_clr_rx_reg;
  reg error_clr_wreq;
  wire error_clr_wack;
  reg rd_ack_d0;
  reg [31:0] rd_dat_d0;
  reg wr_req_d0;
  reg [4:2] wr_adr_d0;
  reg [31:0] wr_dat_d0;

  // Write Channel
  assign wr_req = (psel & pwrite) & ~penable;
  assign wr_addr = paddr;
  assign wr_data = pwdata;
  always @(pstrb)
  ;

  // Read Channel
  assign rd_req = (psel & ~pwrite) & ~penable;
  assign rd_addr = paddr;
  assign prdata = rd_data;
  assign pready = wr_ack | rd_ack;
  assign pslverr = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        rd_ack <= 1'b0;
        rd_data <= 32'b00000000000000000000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 3'b000;
        wr_dat_d0 <= 32'b00000000000000000000000000000000;
      end
    else
      begin
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
      end
  end

  // Register ctrl
  assign ctrl_enable_o = ctrl_enable_reg;
  assign ctrl_lanes_o = ctrl_lanes_reg;
  assign ctrl_clk_div_o = ctrl_clk_div_reg;
  assign ctrl_loopback_o = ctrl_loopback_reg;
  assign ctrl_wack = ctrl_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        ctrl_enable_reg <= 1'b0;
        ctrl_lanes_reg <= 5'b00000;
        ctrl_clk_div_reg <= 8'b00000000;
        ctrl_loopback_reg <= 1'b0;
      end
    else
      if (ctrl_wreq == 1'b1)
        begin
          ctrl_enable_reg <= wr_dat_d0[0];
          ctrl_lanes_reg <= wr_dat_d0[5:1];
          ctrl_clk_div_reg <= wr_dat_d0[13:6];
          ctrl_loopback_reg <= wr_dat_d0[14];
        end
  end

  // Register status

  // Register tx_data
  assign tx_data_data_o = tx_data_data_reg;
  assign tx_data_wack = tx_data_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      tx_data_data_reg <= 8'b00000000;
    else
      if (tx_data_wreq == 1'b1)
        tx_data_data_reg <= wr_dat_d0[7:0];
  end

  // Register rx_data

  // Register error_cnt

  // Register error_clr
  assign error_clr_clr_tx_o = error_clr_clr_tx_reg;
  assign error_clr_clr_rx_o = error_clr_clr_rx_reg;
  assign error_clr_wack = error_clr_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        error_clr_clr_tx_reg <= 1'b0;
        error_clr_clr_rx_reg <= 1'b0;
      end
    else
      if (error_clr_wreq == 1'b1)
        begin
          error_clr_clr_tx_reg <= wr_dat_d0[0];
          error_clr_clr_rx_reg <= wr_dat_d0[1];
        end
  end

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, ctrl_wack, tx_data_wack, error_clr_wack)
  begin
    ctrl_wreq = 1'b0;
    tx_data_wreq = 1'b0;
    error_clr_wreq = 1'b0;
    case (wr_adr_d0[4:2])
    3'b000:
      begin
        // Reg ctrl
        ctrl_wreq = wr_req_d0;
        wr_ack = ctrl_wack;
      end
    3'b001:
      // Reg status
      wr_ack = wr_req_d0;
    3'b010:
      begin
        // Reg tx_data
        tx_data_wreq = wr_req_d0;
        wr_ack = tx_data_wack;
      end
    3'b011:
      // Reg rx_data
      wr_ack = wr_req_d0;
    3'b100:
      // Reg error_cnt
      wr_ack = wr_req_d0;
    3'b101:
      begin
        // Reg error_clr
        error_clr_wreq = wr_req_d0;
        wr_ack = error_clr_wack;
      end
    default:
      wr_ack = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(rd_addr, rd_req, ctrl_enable_reg, ctrl_lanes_reg, ctrl_clk_div_reg, ctrl_loopback_reg, status_tx_busy_i, status_tx_full_i, status_tx_empty_i, status_tx_overflow_i, status_rx_locked_i, status_rx_clk_timeout_i, status_rx_sync_lost_i, status_rx_framing_err_i, status_rx_overflow_i, tx_data_data_reg, rx_data_data_i, rx_data_valid_i, error_cnt_tx_drop_count_i, error_cnt_rx_error_count_i, error_clr_clr_tx_reg, error_clr_clr_rx_reg)
  begin
    // By default ack read requests
    rd_dat_d0 = {32{1'bx}};
    case (rd_addr[4:2])
    3'b000:
      begin
        // Reg ctrl
        rd_ack_d0 = rd_req;
        rd_dat_d0[0] = ctrl_enable_reg;
        rd_dat_d0[5:1] = ctrl_lanes_reg;
        rd_dat_d0[13:6] = ctrl_clk_div_reg;
        rd_dat_d0[14] = ctrl_loopback_reg;
        rd_dat_d0[31:15] = 17'b0;
      end
    3'b001:
      begin
        // Reg status
        rd_ack_d0 = rd_req;
        rd_dat_d0[0] = status_tx_busy_i;
        rd_dat_d0[1] = status_tx_full_i;
        rd_dat_d0[2] = status_tx_empty_i;
        rd_dat_d0[3] = status_tx_overflow_i;
        rd_dat_d0[7:4] = 4'b0;
        rd_dat_d0[8] = status_rx_locked_i;
        rd_dat_d0[9] = status_rx_clk_timeout_i;
        rd_dat_d0[10] = status_rx_sync_lost_i;
        rd_dat_d0[11] = status_rx_framing_err_i;
        rd_dat_d0[12] = status_rx_overflow_i;
        rd_dat_d0[31:13] = 19'b0;
      end
    3'b010:
      begin
        // Reg tx_data
        rd_ack_d0 = rd_req;
        rd_dat_d0[7:0] = tx_data_data_reg;
        rd_dat_d0[31:8] = 24'b0;
      end
    3'b011:
      begin
        // Reg rx_data
        rd_ack_d0 = rd_req;
        rd_dat_d0[7:0] = rx_data_data_i;
        rd_dat_d0[8] = rx_data_valid_i;
        rd_dat_d0[31:9] = 23'b0;
      end
    3'b100:
      begin
        // Reg error_cnt
        rd_ack_d0 = rd_req;
        rd_dat_d0[7:0] = error_cnt_tx_drop_count_i;
        rd_dat_d0[15:8] = error_cnt_rx_error_count_i;
        rd_dat_d0[31:16] = 16'b0;
      end
    3'b101:
      begin
        // Reg error_clr
        rd_ack_d0 = rd_req;
        rd_dat_d0[0] = error_clr_clr_tx_reg;
        rd_dat_d0[1] = error_clr_clr_rx_reg;
        rd_dat_d0[31:2] = 30'b0;
      end
    default:
      rd_ack_d0 = rd_req;
    endcase
  end
endmodule
