#ifndef __CHEBY__MULTIFLEX_REGS__H__
#define __CHEBY__MULTIFLEX_REGS__H__

#define MULTIFLEX_REGS_SIZE 24 /* 0x18 */

/* REG ctrl */
#define MULTIFLEX_REGS_CTRL 0x0UL
#define MULTIFLEX_REGS_CTRL_ENABLE 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_MASK 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_SHIFT 0
#define MULTIFLEX_REGS_CTRL_LANES_MASK 0x3eUL
#define MULTIFLEX_REGS_CTRL_LANES_SHIFT 1
#define MULTIFLEX_REGS_CTRL_CLK_DIV_MASK 0x3fc0UL
#define MULTIFLEX_REGS_CTRL_CLK_DIV_SHIFT 6
#define MULTIFLEX_REGS_CTRL_LOOPBACK 0x4000UL
#define MULTIFLEX_REGS_CTRL_LOOPBACK_MASK 0x4000UL
#define MULTIFLEX_REGS_CTRL_LOOPBACK_SHIFT 14

/* REG status */
#define MULTIFLEX_REGS_STATUS 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_MASK 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_SHIFT 0
#define MULTIFLEX_REGS_STATUS_TX_FULL 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_MASK 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_SHIFT 1
#define MULTIFLEX_REGS_STATUS_TX_EMPTY 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_MASK 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_SHIFT 2
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW 0x8UL
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW_MASK 0x8UL
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW_SHIFT 3
#define MULTIFLEX_REGS_STATUS_RX_LOCKED 0x100UL
#define MULTIFLEX_REGS_STATUS_RX_LOCKED_MASK 0x100UL
#define MULTIFLEX_REGS_STATUS_RX_LOCKED_SHIFT 8
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT 0x200UL
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT_MASK 0x200UL
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT_SHIFT 9
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST 0x400UL
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST_MASK 0x400UL
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST_SHIFT 10
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR 0x800UL
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR_MASK 0x800UL
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR_SHIFT 11
#define MULTIFLEX_REGS_STATUS_RX_OVERFLOW 0x1000UL
#define MULTIFLEX_REGS_STATUS_RX_OVERFLOW_MASK 0x1000UL
#define MULTIFLEX_REGS_STATUS_RX_OVERFLOW_SHIFT 12

/* REG tx_data */
#define MULTIFLEX_REGS_TX_DATA 0x8UL
#define MULTIFLEX_REGS_TX_DATA_DATA_MASK 0xffUL
#define MULTIFLEX_REGS_TX_DATA_DATA_SHIFT 0

/* REG rx_data */
#define MULTIFLEX_REGS_RX_DATA 0xcUL
#define MULTIFLEX_REGS_RX_DATA_DATA_MASK 0xffUL
#define MULTIFLEX_REGS_RX_DATA_DATA_SHIFT 0
#define MULTIFLEX_REGS_RX_DATA_VALID 0x100UL
#define MULTIFLEX_REGS_RX_DATA_VALID_MASK 0x100UL
#define MULTIFLEX_REGS_RX_DATA_VALID_SHIFT 8

/* REG error_cnt */
#define MULTIFLEX_REGS_ERROR_CNT 0x10UL
#define MULTIFLEX_REGS_ERROR_CNT_TX_DROP_COUNT_MASK 0xffUL
#define MULTIFLEX_REGS_ERROR_CNT_TX_DROP_COUNT_SHIFT 0
#define MULTIFLEX_REGS_ERROR_CNT_RX_ERROR_COUNT_MASK 0xff00UL
#define MULTIFLEX_REGS_ERROR_CNT_RX_ERROR_COUNT_SHIFT 8

/* REG error_clr */
#define MULTIFLEX_REGS_ERROR_CLR 0x14UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX 0x1UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX_MASK 0x1UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX_SHIFT 0
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX 0x2UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX_MASK 0x2UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX_SHIFT 1

#ifndef __ASSEMBLER__
struct multiflex_regs {
  /* [0x0]: REG (rw) */
  uint32_t ctrl;

  /* [0x4]: REG (ro) */
  uint32_t status;

  /* [0x8]: REG (rw) */
  uint32_t tx_data;

  /* [0xc]: REG (ro) */
  uint32_t rx_data;

  /* [0x10]: REG (ro) */
  uint32_t error_cnt;

  /* [0x14]: REG (rw) */
  uint32_t error_clr;
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__MULTIFLEX_REGS__H__ */
