#ifndef __CHEBY__MULTIFLEX_REGS__H__
#define __CHEBY__MULTIFLEX_REGS__H__

#define MULTIFLEX_REGS_SIZE 12 /* 0xc */

/* REG ctrl */
#define MULTIFLEX_REGS_CTRL 0x0UL
#define MULTIFLEX_REGS_CTRL_ENABLE 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_MASK 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_SHIFT 0
#define MULTIFLEX_REGS_CTRL_LANES_MASK 0x3eUL
#define MULTIFLEX_REGS_CTRL_LANES_SHIFT 1
#define MULTIFLEX_REGS_CTRL_CLK_DIV_MASK 0x3fc0UL
#define MULTIFLEX_REGS_CTRL_CLK_DIV_SHIFT 6

/* REG status */
#define MULTIFLEX_REGS_STATUS 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_MASK 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_SHIFT 0
#define MULTIFLEX_REGS_STATUS_TX_FULL 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_MASK 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_SHIFT 1
#define MULTIFLEX_REGS_STATUS_TX_EMPTY 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_MASK 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_SHIFT 2

/* REG tx_data */
#define MULTIFLEX_REGS_TX_DATA 0x8UL
#define MULTIFLEX_REGS_TX_DATA_DATA_MASK 0xffUL
#define MULTIFLEX_REGS_TX_DATA_DATA_SHIFT 0

#ifndef __ASSEMBLER__
struct multiflex_regs {
  /* [0x0]: REG (rw) */
  uint32_t ctrl;

  /* [0x4]: REG (ro) */
  uint32_t status;

  /* [0x8]: REG (rw) */
  uint32_t tx_data;
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__MULTIFLEX_REGS__H__ */
