#ifndef __CHEBY__MULTIFLEX_REGS__H__
#define __CHEBY__MULTIFLEX_REGS__H__

#define MULTIFLEX_REGS_SIZE 24576 /* 0x6000 = 24KB */

/* REG ctrl */
#define MULTIFLEX_REGS_CTRL 0x0UL
#define MULTIFLEX_REGS_CTRL_ENABLE 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_MASK 0x1UL
#define MULTIFLEX_REGS_CTRL_ENABLE_SHIFT 0
#define MULTIFLEX_REGS_CTRL_LANES_TX_MASK 0x3eUL
#define MULTIFLEX_REGS_CTRL_LANES_TX_SHIFT 1
#define MULTIFLEX_REGS_CTRL_LANES_RX_MASK 0x7c0UL
#define MULTIFLEX_REGS_CTRL_LANES_RX_SHIFT 6
#define MULTIFLEX_REGS_CTRL_CLK_DIV_MASK 0x7f800UL
#define MULTIFLEX_REGS_CTRL_CLK_DIV_SHIFT 11
#define MULTIFLEX_REGS_CTRL_LOOPBACK 0x80000UL
#define MULTIFLEX_REGS_CTRL_LOOPBACK_MASK 0x80000UL
#define MULTIFLEX_REGS_CTRL_LOOPBACK_SHIFT 19

/* REG status */
#define MULTIFLEX_REGS_STATUS 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_MASK 0x1UL
#define MULTIFLEX_REGS_STATUS_TX_BUSY_SHIFT 0
#define MULTIFLEX_REGS_STATUS_TX_FULL 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_MASK 0x2UL
#define MULTIFLEX_REGS_STATUS_TX_FULL_SHIFT 1
#define MULTIFLEX_REGS_STATUS_TX_EMPTY 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_MASK 0x4UL
#define MULTIFLEX_REGS_STATUS_TX_EMPTY_SHIFT 2
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW 0x8UL
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW_MASK 0x8UL
#define MULTIFLEX_REGS_STATUS_TX_OVERFLOW_SHIFT 3
#define MULTIFLEX_REGS_STATUS_RX_LOCKED 0x100UL
#define MULTIFLEX_REGS_STATUS_RX_LOCKED_MASK 0x100UL
#define MULTIFLEX_REGS_STATUS_RX_LOCKED_SHIFT 8
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT 0x200UL
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT_MASK 0x200UL
#define MULTIFLEX_REGS_STATUS_RX_CLK_TIMEOUT_SHIFT 9
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST 0x400UL
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST_MASK 0x400UL
#define MULTIFLEX_REGS_STATUS_RX_SYNC_LOST_SHIFT 10
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR 0x800UL
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR_MASK 0x800UL
#define MULTIFLEX_REGS_STATUS_RX_FRAMING_ERR_SHIFT 11

/* REG tx_data */
#define MULTIFLEX_REGS_TX_DATA 0x8UL
#define MULTIFLEX_REGS_TX_DATA_DATA_MASK 0xffUL
#define MULTIFLEX_REGS_TX_DATA_DATA_SHIFT 0

/* REG rx_data */
#define MULTIFLEX_REGS_RX_DATA 0xcUL
#define MULTIFLEX_REGS_RX_DATA_DATA_MASK 0xffUL
#define MULTIFLEX_REGS_RX_DATA_DATA_SHIFT 0
#define MULTIFLEX_REGS_RX_DATA_VALID 0x100UL
#define MULTIFLEX_REGS_RX_DATA_VALID_MASK 0x100UL
#define MULTIFLEX_REGS_RX_DATA_VALID_SHIFT 8

/* REG error_cnt */
#define MULTIFLEX_REGS_ERROR_CNT 0x10UL
#define MULTIFLEX_REGS_ERROR_CNT_TX_DROP_COUNT_MASK 0xffUL
#define MULTIFLEX_REGS_ERROR_CNT_TX_DROP_COUNT_SHIFT 0
#define MULTIFLEX_REGS_ERROR_CNT_RX_ERROR_COUNT_MASK 0xff00UL
#define MULTIFLEX_REGS_ERROR_CNT_RX_ERROR_COUNT_SHIFT 8

/* REG error_clr */
#define MULTIFLEX_REGS_ERROR_CLR 0x14UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX 0x1UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX_MASK 0x1UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_TX_SHIFT 0
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX 0x2UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX_MASK 0x2UL
#define MULTIFLEX_REGS_ERROR_CLR_CLR_RX_SHIFT 1

/* REG tx_len */
#define MULTIFLEX_REGS_TX_LEN 0x18UL
#define MULTIFLEX_REGS_TX_LEN_LEN_MASK 0x7ffUL
#define MULTIFLEX_REGS_TX_LEN_LEN_SHIFT 0

/* REG rx_count */
#define MULTIFLEX_REGS_RX_COUNT 0x1cUL
#define MULTIFLEX_REGS_RX_COUNT_COUNT_MASK 0x7ffUL
#define MULTIFLEX_REGS_RX_COUNT_COUNT_SHIFT 0

/* REG tx_buf */
#define MULTIFLEX_REGS_TX_BUF 0x2000UL
#define MULTIFLEX_REGS_TX_BUF_SIZE 1 /* 0x1 */

/* REG data */
#define MULTIFLEX_REGS_TX_BUF_DATA 0x0UL

/* REG rx_buf */
#define MULTIFLEX_REGS_RX_BUF 0x4000UL
#define MULTIFLEX_REGS_RX_BUF_SIZE 1 /* 0x1 */

/* REG data */
#define MULTIFLEX_REGS_RX_BUF_DATA 0x0UL

#ifndef __ASSEMBLER__
struct multiflex_regs {
  /* [0x0]: REG (rw) */
  uint32_t ctrl;

  /* [0x4]: REG (ro) */
  uint32_t status;

  /* [0x8]: REG (rw) */
  uint32_t tx_data;

  /* [0xc]: REG (ro) */
  uint32_t rx_data;

  /* [0x10]: REG (ro) */
  uint32_t error_cnt;

  /* [0x14]: REG (rw) */
  uint32_t error_clr;

  /* [0x18]: REG (rw) */
  uint32_t tx_len;

  /* [0x1c]: REG (ro) */
  uint32_t rx_count;

  /* padding to: 8192 Bytes */
  uint32_t __padding_0[2040];

  /* [0x2000]: MEMORY */
  struct tx_buf {
    /* [0x0]: REG (wo) */
    uint8_t data;
  } tx_buf[2048];

  /* padding to: 8192 Bytes */
  uint32_t __padding_1[1536];

  /* [0x4000]: MEMORY */
  struct rx_buf {
    /* [0x0]: REG (ro) */
    uint8_t data;
  } rx_buf[2048];

  /* padding to: 16384 Bytes */
  uint32_t __padding_2[1536];
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__MULTIFLEX_REGS__H__ */
